"""initial_schema

Revision ID: c118f4921aa4
Revises:
Create Date: 2026-06-21 14:49:16.272508

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "c118f4921aa4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
