"""add_created_at_to_labels

Revision ID: c53f5879c3b0
Revises: c118f4921aa4
Create Date: 2026-06-21 14:50:46.212173

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c53f5879c3b0"
down_revision: str | Sequence[str] | None = "c118f4921aa4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default nécessaire : la table a des lignes existantes.
    # Sans ça, Postgres refuse d'ajouter une colonne NOT NULL sans valeur pour les lignes existantes.
    op.add_column(
        "labels",
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("labels", "created_at")
    # ### end Alembic commands ###
