api:
  image:
    tag: main
  reload: true
  env:
    LOG_LEVEL: debug

web:
  image:
    tag: main
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"

postgres:
  enabled: true
  pvc:
    enabled: false

db:
  name: taskhorizon
  user: postgres
  password: testpassword

ingress:
  enabled: false
