api:
  replicaCount: 2
  reload: false
  pdb:
    enabled: true
    minAvailable: 1

web:
  replicaCount: 2
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "external"
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
  pdb:
    enabled: true
    minAvailable: 1

postgres:
  enabled: false

db:
  name: taskhorizon
  user: taskhorizon
  # password et externalHost injectés via --set en CI

ingress:
  enabled: false
