apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "taskhorizon.componentName" (dict "Release" .Release "component" "api-config") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "taskhorizon.labels" . | nindent 4 }}
data:
  DATABASE_NAME: {{ .Values.db.name | quote }}
  API_HOST: {{ .Values.api.env.API_HOST | quote }}
  API_PORT: {{ .Values.api.env.API_PORT | quote }}
  LOG_LEVEL: {{ .Values.api.env.LOG_LEVEL | quote }}
  JWT_EXPIRE_HOURS: {{ .Values.auth.jwtExpireHours | quote }}
  ADMIN_EMAIL: {{ .Values.auth.adminEmail | quote }}
