{{- if .Values.web.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "taskhorizon.componentName" (dict "Release" .Release "component" "web") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "taskhorizon.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "taskhorizon.componentName" (dict "Release" .Release "component" "web") }}
  minReplicas: {{ .Values.web.hpa.minReplicas }}
  maxReplicas: {{ .Values.web.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.web.hpa.targetCPUUtilizationPercentage }}
{{- end }}
