{{- if .Values.web.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "taskhorizon.componentName" (dict "Release" .Release "component" "web") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "taskhorizon.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  minAvailable: {{ .Values.web.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "taskhorizon.selectorLabels" (dict "Release" .Release "component" "web") | nindent 6 }}
{{- end }}
