{{- if not .Values.db.existingSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taskhorizon.componentName" (dict "Release" .Release "component" "db-credentials") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "taskhorizon.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ required "db.user must be set" .Values.db.user | b64enc | quote }}
  password: {{ required "db.password must be set when not using existingSecret" .Values.db.password | b64enc | quote }}
{{- end }}
