apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskhorizon.componentName" (dict "Release" .Release "component" "web") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "taskhorizon.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.web.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "taskhorizon.selectorLabels" (dict "Release" .Release "component" "web") | nindent 4 }}
